In [1]:
import numpy as np

from scipy.spatial.distance import cdist

In [14]:
def my_cdist_func(A, B):
    LA, WA = A.shape
    LB, WB = B.shape
    
    ret_array = np.zeros((LA,LB))
    for i in range(LA):
        aux = np.array([A[i]-B[j] for j in range(LB)])
        ret_array[i] = np.sqrt(np.sum(np.power(aux,2),axis=1))
    
    return ret_array

In [5]:
# Aqui eu coloquei uma matriz qlqr pra testar, ve se vc tem algo ai
data = np.genfromtxt("iris.csv", delimiter=',')
L, W = data.shape

A = data[:int(L/2)]
B = data[int(L/2):]

In [6]:
sp_cdist = cdist(A,B)

In [7]:
sp_cdist.shape

(75, 75)

In [15]:
my_cdist = my_cdist_func(A,B)

In [16]:
my_cdist.shape

(75, 75)

In [17]:
sp_cdist

array([[3.59722115, 4.04722127, 4.24499706, ..., 4.45982062, 4.65080638,
        4.14004831],
       [3.65102725, 4.08044115, 4.29534632, ..., 4.49888875, 4.71805044,
        4.15331193],
       [3.8340579 , 4.27317212, 4.46989933, ..., 4.66154481, 4.84871117,
        4.29883705],
       ...,
       [0.77459667, 0.6       , 0.678233  , ..., 0.79372539, 1.30766968,
        0.73484692],
       [0.64807407, 0.73484692, 0.86023253, ..., 1.04403065, 1.43874946,
        0.77459667],
       [0.26457513, 0.65574385, 0.8660254 , ..., 1.14891253, 1.58113883,
        1.07238053]])

In [18]:
my_cdist

array([[3.59722115, 4.04722127, 4.24499706, ..., 4.45982062, 4.65080638,
        4.14004831],
       [3.65102725, 4.08044115, 4.29534632, ..., 4.49888875, 4.71805044,
        4.15331193],
       [3.8340579 , 4.27317212, 4.46989933, ..., 4.66154481, 4.84871117,
        4.29883705],
       ...,
       [0.77459667, 0.6       , 0.678233  , ..., 0.79372539, 1.30766968,
        0.73484692],
       [0.64807407, 0.73484692, 0.86023253, ..., 1.04403065, 1.43874946,
        0.77459667],
       [0.26457513, 0.65574385, 0.8660254 , ..., 1.14891253, 1.58113883,
        1.07238053]])

In [25]:
compare = (sp_cdist == my_cdist)

compare

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [26]:
compare.all()

True